CREATE TABLE `novedadesr_historico` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `IdNovedadesE` int NOT NULL,
  `Area` enum('Administrativa','Operativa') NOT NULL,
  `IdSector` int NOT NULL,
  `IdEmpleado` int NOT NULL,
  `Fecha` date NOT NULL,
  `Hs50` varchar(5) DEFAULT NULL,
  `Hs100` varchar(5) DEFAULT NULL,
  `GuardiasDiurnas` decimal(3,2) DEFAULT NULL,
  `GuardiasNocturnas` decimal(3,2) DEFAULT NULL,
  `GuardiasPasivas` decimal(3,2) DEFAULT NULL,
  `Monto` decimal(10,2) DEFAULT NULL,
  `IdGuardia` int DEFAULT NULL,
  `IdParcial` tinyint DEFAULT NULL,
  `IdNomina` int NOT NULL,
  `IdTurno` int NOT NULL,
  `IdCategoria` int NOT NULL,
  `IdEstado` int NOT NULL,
  `ObservacionesEstado` text,
  `IdSupervisor` int NOT NULL,
  `MinutosAl50` int DEFAULT NULL,
  `MinutosAl100` int DEFAULT NULL,
  `MinutosGD` int DEFAULT NULL,
  `MinutosGN` int DEFAULT NULL,
  `Inicio` datetime DEFAULT NULL,
  `Fin` datetime DEFAULT NULL,
  `IdMotivo` int DEFAULT NULL,
  `IdReemplazo` int DEFAULT NULL,
  `Observaciones` text,
  `CreadoPorAdmin` tinyint DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=118 DEFAULT CHARSET=latin1;
